const projects = [
    {
      id: "1",
      name: "Luxury Villa",
      type: "Real Estate",
      description: "A modern villa with a private pool and ocean view.",
      price: "$500,000",
      image: ["/images/villa1.jpg", "/images/villa2.jpg"],
    },
    {
      id: "2",
      name: "Tech Startup Website",
      type: "Web Development",
      description: "A responsive website for a tech startup.",
      price: "$2,000",
      image: ["/images/startup1.jpg", "/images/startup2.jpg"],
    },
    {
      id: "3",
      name: "E-commerce Mobile App",
      type: "Software Development",
      description: "A shopping app with secure payment integration.",
      price: "$10,000",
      image: ["/images/ecommerce1.jpg", "/images/ecommerce2.jpg"],
    },
    {
      id: "4",
      name: "AI Chatbot",
      type: "Artificial Intelligence",
      description: "A chatbot powered by AI to automate customer support.",
      price: "$5,500",
      image: ["/images/chatbot1.jpg", "/images/chatbot2.jpg"],
    },
    {
      id: "5",
      name: "Cloud Storage Solution",
      type: "Cloud Computing",
      description: "A secure cloud storage solution for enterprises.",
      price: "$15,000",
      image: ["/images/cloud1.jpg", "/images/cloud2.jpg"],
    },
    {
      id: "6",
      name: "Social Media Platform",
      type: "Web Application",
      description: "A platform to connect and share content globally.",
      price: "$50,000",
      image: ["/images/social1.jpg", "/images/social2.jpg"],
    },
    {
      id: "7",
      name: "Crypto Trading App",
      type: "Finance",
      description: "A cryptocurrency trading platform with real-time data.",
      price: "$25,000",
      image: ["/images/crypto1.jpg", "/images/crypto2.jpg"],
    },
    {
      id: "8",
      name: "E-learning Platform",
      type: "Education",
      description: "An interactive learning platform with video courses.",
      price: "$30,000",
      image: ["/images/elearning1.jpg", "/images/elearning2.jpg"],
    },
    {
      id: "9",
      name: "Restaurant Booking System",
      type: "Hospitality",
      description: "A system to manage restaurant reservations online.",
      price: "$7,500",
      image: ["/images/restaurant1.jpg", "/images/restaurant2.jpg"],
    },
    {
      id: "10",
      name: "Fitness Tracker App",
      type: "Health & Wellness",
      description: "An app to track workouts, nutrition, and progress.",
      price: "$12,000",
      image: ["/images/fitness1.jpg", "/images/fitness2.jpg"],
    },
    {
      id: "11",
      name: "Smart Home Automation",
      type: "IoT",
      description: "A system to control home devices remotely.",
      price: "$40,000",
      image: ["/images/smarthome1.jpg", "/images/smarthome2.jpg"],
    },
    {
      id: "12",
      name: "Car Rental App",
      type: "Transport",
      description: "An application to rent cars with GPS tracking.",
      price: "$18,000",
      image: ["/images/car1.jpg", "/images/car2.jpg"],
    },
    {
      id: "13",
      name: "Tourism Website",
      type: "Travel",
      description: "A website to explore travel destinations and book trips.",
      price: "$6,000",
      image: ["/images/tourism1.jpg", "/images/tourism2.jpg"],
    },
    {
      id: "14",
      name: "Gaming Portal",
      type: "Entertainment",
      description: "An online gaming hub with leaderboards and challenges.",
      price: "$22,000",
      image: ["/images/gaming1.jpg", "/images/gaming2.jpg"],
    },
    {
      id: "15",
      name: "Job Recruitment System",
      type: "HR",
      description: "A system for job postings and applicant tracking.",
      price: "$8,500",
      image: ["/images/jobs1.jpg", "/images/jobs2.jpg"],
    },
    {
      id: "16",
      name: "Music Streaming App",
      type: "Media",
      description: "A music app with playlists and offline mode.",
      price: "$19,000",
      image: ["/images/music1.jpg", "/images/music2.jpg"],
    },
    {
      id: "17",
      name: "Virtual Reality Tour",
      type: "VR",
      description: "A VR-based interactive tour experience.",
      price: "$45,000",
      image: ["/images/vr1.jpg", "/images/vr2.jpg"],
    },
    {
      id: "18",
      name: "Legal Document Generator",
      type: "LegalTech",
      description: "A tool to generate legal contracts and agreements.",
      price: "$9,000",
      image: ["/images/legal1.jpg", "/images/legal2.jpg"],
    },
    {
      id: "19",
      name: "Stock Market Analyzer",
      type: "Finance",
      description: "A stock analysis tool with AI-driven predictions.",
      price: "$28,000",
      image: ["/images/stock1.jpg", "/images/stock2.jpg"],
    },
    {
      id: "20",
      name: "Custom CRM Software",
      type: "Business",
      description: "A custom CRM system for sales and customer management.",
      price: "$35,000",
      image: ["/images/crm1.jpg", "/images/crm2.jpg"],
    },
  ];
  